theme: jekyll-theme-hacker
name: Rodrigo Moya @ github
description: From lost to the river
avatar: https://avatars.githubusercontent.com/u/1873039?s=460&u=ea0996c219fd5a1e3ca43b162d906990fc4eb84f&v=4

footer-links:
  dribbble:
  email: romoya at microsoft.com
  facebook:
  flickr:
  github: rodrmoya
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: rodrigo_moya
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/